name: Run clang-tidy

on:
  push:
    paths:
      - '**.cpp'
      - '**.cxx'
      - '**.cc'
      - '**.c'
      - '**.h'
      - '**.hpp'
      - '**/CMakeLists.txt'
  pull_request:
    branches:
      - master

jobs:
  clang-tidy-scan:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0

      # see: ./build.sh --help
      - name: Generate files
        id: suffix
        run: |
          build_linux/clang-tidy/build.sh

      - name: clang-tidy review
        uses: ZedThree/clang-tidy-review@v0.7.1
        id: review
        with:
          # List of packages to install
          apt_packages: |
            install, ninja-build, doxygen, graphviz, libcurl4-openssl-dev, libprotobuf-dev, libprotoc-dev, protobuf-compiler, libhdf5-dev, qt5-default, jq
          build_dir: ${GITHUB_WORKSPACE}/_build
          exclude: ${GITHUB_WORKSPACE}/_build/*, ${GITHUB_WORKSPACE}/thirdparty/*
          max_comments: 100

      # https://github.com/mxschmitt/action-tmate#only-on-failure
      # To debug failures, use either the Web shell link or SSH to the address given on this step,
      # and press 'Q' or 'Ctrl+C' to continue.
      - name: Setup SSH session
        #if: ${{ always() }}
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3.11
        with:
          sudo: true
