name: Run clang-tidy after download

on:
  workflow_call:

jobs:
  clang-tidy-scan-download:
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build doxygen graphviz libcurl4-openssl-dev libprotobuf-dev libprotoc-dev protobuf-compiler libhdf5-dev qt5-default
          sudo apt-get install jq clang-tidy

      - name: Display version info
        run: |
          echo $(g++ --version)
          echo $(clang --version)
          echo $(cmake --version)
          echo $(clang-tidy --version)

      # https://github.com/actions/download-artifact
      - name: Download the built directory
        uses: actions/download-artifact@v3
        with:
          name: ecal-dir.tar.gz

      - name: Extract the tarball archive
        run: tar -xzf ecal.tar.gz && cd ecal

      # https://github.com/Ana06/get-changed-files
      - name: Detect the changeset
        id: changed_files
        uses: Ana06/get-changed-files@v2.1.0

      # see: ./build.sh --help
      - name: Run clang-tidy on the changeset
        id: suffix
        run: |
          cd ecal && build_linux/clang-tidy/build.sh -a -f ${{ steps.changed_files.outputs.added_modified }}

      # https://github.com/actions/upload-artifact
      # If make or clang-tidy is never called, artifact upload will fail (no log files) with just a warning.
      - name: Archive logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: logs_${{ steps.suffix.outputs.timestamp }}
          path: _build/log_*.txt
          if-no-files-found: warn

      # https://github.com/mxschmitt/action-tmate#only-on-failure
      # To debug failures, use either the Web shell link or SSH to the address given on this step,
      # and press 'Q' or 'Ctrl+C' to continue.
      - name: Setup SSH session
        #if: ${{ always() }}
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3.11
        with:
          sudo: true
